[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
ghosttip = "C7GTb7VYxdrG38MKGPxLGb14X199btYZ5kDerSGiayW5"

[programs.localnet]
ghosttip = "GhsTipQhNGUc8vN3WtNpe6VbMTaZh6UgJcy3q8LjMXyE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
