[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "CAUVfW4YopPjuiWxWVHP2R4Wj8XKUKSysHhaipGGcCRA"
ghosttip = "GhsTipQhNGUc8vN3WtNpe6VbMTaZh6UgJcy3q8LjMXyE"

[programs.devnet]
vault = "CAUVfW4YopPjuiWxWVHP2R4Wj8XKUKSysHhaipGGcCRA"
ghosttip = "GhsTipQhNGUc8vN3WtNpe6VbMTaZh6UgJcy3q8LjMXyE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
